### ISSUE TITLE
feat: Visual Feedback and Loading States for AI-Powered Chat

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#1022]
# Enhancement: Visual Feedback and Loading States for AI-Powered Chat

## Description 📹

The chat interface lacks clear visual feedback for user actions and loading states. Users need better indicators for message sending, processing, and connection status.

## Proposed Actions 🛠️

1. **Fork and Create Branch**:  
   ```bash
   git checkout -b fix-visual-feedback
   ```

2. **Implement Changes**:  
```css:theme/css/chat.css
.message.loading {
  display: flex;
  align-items: center;
  gap: 8px;
}

.loading-dots {
  display: flex;
  gap: 4px;
}

.loading-dots span {
  width: 8px;
  height: 8px;
  background: currentColor;
  border-radius: 50%;
  animation: bounce 1.4s infinite ease-in-out;
}

/* Add different delays for each dot */
.loading-dots span:nth-child(1) {
  animation-delay: -0.32s;
}

.loading-dots span:nth-child(2) {
  animation-delay: -0.16s;
}

/* Add the bounce animation */
@keyframes bounce {
  0%, 80%, 100% {
    transform: scale(0);
  }
  40% {
    transform: scale(1);
  }
}
```

   ```javascript:theme/chat.js
   showLoadingIndicator() {
     const loadingElement = document.createElement("div");
     loadingElement.className = "message loading";
     loadingElement.innerHTML = `
       Thinking
       <div class="loading-dots">
         <span></span><span></span><span></span>
       </div>
     `;
     document.getElementById("chat-messages").appendChild(loadingElement);
     this.scrollToBottom();
   }
   ```
   
   You're free to also add any changes that are aligned with this feature request of improving user feedback and global UI.

3. **Run Tests and Commit Changes**

Visual tests are enough to ensure this works well. Ask a question and verify the animation is present.

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.
