### ISSUE TITLE
feat: Implement theme variable support for AI-Powered Chat interface

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#1023]
## Description 📹

The chat interface currently uses hardcoded colors which don't respect the mdBook theme system. We need to implement proper theme variable support by:
1. Adding chat-specific variables to each theme in `variables.css`
2. Updating `chat.css` to use these theme variables
3. Ensuring proper fallback values for compatibility

## Proposed Actions 🛠️

1. **Fork and Create Branch**:  
   ```bash
   git checkout -b add-chat-theme-support
   ```

2. **Add Theme Variables**:  
   Add the following variables to each theme class (`.ayu`, `.coal`, `.light`, `.navy`, `.rust`) in `variables.css`:
```css:theme/css/variables.css
   .ayu {
     /* ... existing variables ... */
  --chat-user-msg-bg: #4a86e8;
  --chat-user-msg-text: white;
  --chat-ai-msg-bg: #424242;
  --chat-ai-msg-text: white;
  --chat-code-bg: var(--theme-popup-bg);
  --chat-scrollbar: var(--scrollbar);
  --chat-scrollbar-hover: var(--icons-hover);
  --chat-bg: var(--bg);
   }
   
   .coal {
  --chat-user-msg-bg: #3473ad;
  --chat-user-msg-text: white;
  --chat-ai-msg-bg: #292c2f;
  --chat-ai-msg-text: var(--fg);
  --chat-code-bg: var(--theme-popup-bg);
  --chat-scrollbar: var(--scrollbar);
  --chat-scrollbar-hover: var(--icons-hover);
  --chat-bg: var(--bg);
  }
  
  .light {
  --chat-user-msg-bg: #007AFF;  /* iOS blue */
  --chat-user-msg-text: white;
  --chat-ai-msg-bg: #E9E9EB;    /* iMessage grey */
  --chat-ai-msg-text: #000000;
  --chat-code-bg: var(--theme-popup-bg);
  --chat-scrollbar: var(--scrollbar);
  --chat-scrollbar-hover: var(--icons-hover);
  --chat-bg: var(--bg);
 }
 
 .navy {
  --chat-user-msg-bg: #2b79a2;
  --chat-user-msg-text: white;
  --chat-ai-msg-bg: #282d3f;
  --chat-ai-msg-text: var(--fg);
  --chat-code-bg: var(--theme-popup-bg);
  --chat-scrollbar: var(--scrollbar);
  --chat-scrollbar-hover: var(--icons-hover);
  --chat-bg: var(--bg);
  }
  
  .rust {
   --chat-user-msg-bg: #e69f67;
  --chat-user-msg-text: white;
  --chat-ai-msg-bg: #c4cbd2;
  --chat-ai-msg-text: var(--fg);
  --chat-code-bg: var(--theme-popup-bg);
  --chat-scrollbar: var(--scrollbar);
  --chat-scrollbar-hover: var(--icons-hover);
  --chat-bg: var(--bg);
  }
```

   Customize colors for each theme:
   - Light theme should use iMessage-like colors
   - Dark themes should use appropriate dark mode colors
   - Use existing theme variables where possible

3. **Update Chat Styles**:  
   Replace hardcoded colors in `chat.css` with theme variables:
   ```css:theme/css/chat.css
   #chat-window {
     background-color: var(--bg, #2b2b2b);
   }

   #chat-input {
     background-color: var(--chat-input-bg, var(--bg));
   }

   #message-input {
     background-color: var(--chat-input-bg, var(--bg));
     color: var(--chat-text);
   }

   .message.user {
     background-color: var(--chat-user-msg-bg, #4a86e8);
     color: var(--chat-user-msg-text, white);
   }

   .message.ai {
     background-color: var(--chat-ai-msg-bg, #424242);
     color: var(--chat-ai-msg-text, white);
   }

   .message .content pre {
     background-color: var(--chat-code-bg, #2b2b2b);
   }
   ```

## Required 📋

- Knowledge of CSS and CSS variables
- Understanding of mdBook theme system
- Test changes in all themes (ayu, coal, light, navy, rust)
- Ensure proper fallback values for compatibility
- Maintain accessibility standards (sufficient contrast ratios)
- Test theme switching functionality

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

## Testing Checklist ✅

- [ ] Test in all available themes
- [ ] Verify proper color contrast
- [ ] Check theme switching behavior

Thank you for your contribution! 🙏
